name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_REPO: doku9652/aws # Replace with your Docker Hub repository name
  DOCKER_HUB_USERNAME: doku9652 # Replace with your Docker Hub username
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }} # Set this secret in your GitHub repository settings

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_HUB_REPO }}:cv2.onnxruntime
